# Generated by Django 2.2.6 on 2019-11-08 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViberUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viber_id', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('language', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('is_bloked', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
