# Generated by Django 2.2.6 on 2019-11-22 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vbot', '0002_auto_20191112_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viberuser',
            options={'verbose_name_plural': 'Viber пользователи'},
        ),
    ]
